# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bfosc.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
try:
   from PyQt5 import QtCore, QtGui, QtWidgets
except:
   from PyQt6 import QtCore, QtGui, QtWidgets


class WvClibWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1430, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        ## arc button
        self.toolButton_load_arc = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_load_arc.setGeometry(QtCore.QRect(10, 20, 80, 22))
        self.toolButton_load_arc.setObjectName("toolButton_load_arc")
        self.lineEdit_arc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_arc.setGeometry(QtCore.QRect(90, 20, 420, 21))
        self.lineEdit_arc.setObjectName("lineEdit_arc")
        ## linelist button
        self.toolButton_load_linelist = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_load_linelist.setGeometry(QtCore.QRect(10, 45, 80, 22))
        self.toolButton_load_linelist.setObjectName("toolButton_load_linelist")
        self.lineEdit_linelist = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_linelist.setGeometry(QtCore.QRect(90, 45, 420, 21))
        self.lineEdit_linelist.setObjectName("lineEdit_linelist")
        ## show order button
        self.lineEdit_order = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_order.setEnabled(True)
        self.lineEdit_order.setGeometry(QtCore.QRect(511, 70, 113, 21))
        ## table widget
        self.tableWidget_files = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_files.setGeometry(QtCore.QRect(10, 70, 500, 451))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_files.setFont(font)
        try:
            self.tableWidget_files.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents) ###pyqt5
        except:
            self.tableWidget_files.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents) ###pyqt5
        self.tableWidget_files.setAlternatingRowColors(True)
        self.tableWidget_files.setObjectName("tableWidget_files")
        self.tableWidget_files.setColumnCount(0)
        self.tableWidget_files.setRowCount(0)
        self.tableWidget_files.horizontalHeader().setCascadingSectionResizes(True)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(511, 110, 134, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_update_table = QtWidgets.QPushButton(self.layoutWidget)
        try:
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed) ###pyqt5
        except:
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed) ###pyqt6
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.pushButton_update_table.sizePolicy().hasHeightForWidth())
        self.pushButton_update_table.setSizePolicy(sizePolicy)
        self.pushButton_update_table.setObjectName("pushButton_update_table")
        self.verticalLayout.addWidget(self.pushButton_update_table)
        self.pushButton_proc_bias = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_proc_bias.setObjectName("pushButton_proc_bias")
        self.verticalLayout.addWidget(self.pushButton_proc_bias)
        self.pushButton_proc_flat = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_proc_flat.setObjectName("pushButton_proc_flat")
        self.verticalLayout.addWidget(self.pushButton_proc_flat)
        self.pushButton_clear_line = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clear_line.setObjectName("pushButton_clear_line")
        self.verticalLayout.addWidget(self.pushButton_clear_line)
        self.pushButton_add_line = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_add_line.setObjectName("pushButton_add_line")
        self.verticalLayout.addWidget(self.pushButton_add_line)
        self.pushButton_del_line = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_del_line.setObjectName("pushButton_del_line")
        self.verticalLayout.addWidget(self.pushButton_del_line)
        self.pushButton_save_line = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save_line.setObjectName("pushButton_save_line")
        self.verticalLayout.addWidget(self.pushButton_save_line)
        self.pushButton_proc_all = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_proc_all.setObjectName("pushButton_proc_all")
        self.verticalLayout.addWidget(self.pushButton_proc_all)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_order.setFont(font)
        self.lineEdit_order.setObjectName("lineEdit_order")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1430, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"Manually Calibrate Wave"))
        self.pushButton_update_table.setText(_translate("MainWindow", "update table"))
        self.pushButton_proc_bias.setText(_translate("MainWindow", "process bias"))
        self.pushButton_proc_flat.setText(_translate("MainWindow", "process flat"))
        self.pushButton_clear_line.setText(_translate("MainWindow", "clear lines"))
        self.pushButton_add_line.setText(_translate("MainWindow", "add line"))
        self.pushButton_del_line.setText(_translate("MainWindow", "del line"))
        self.pushButton_save_line.setText(_translate("MainWindow", "save lines"))
        self.pushButton_proc_all.setText(_translate("MainWindow", "process all"))
        self.toolButton_load_arc.setText(_translate("MainWindow", "ARC..."))
        self.toolButton_load_linelist.setText(_translate("MainWindow", "LINELIST..."))
