# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bfosc.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
try:
   from PyQt5 import QtCore, QtGui, QtWidgets
except:
   from PyQt6 import QtCore, QtGui, QtWidgets


class WvClibWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1300, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        ## arc button
        self.toolButton_load_arc = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_load_arc.setGeometry(QtCore.QRect(10, 20, 80, 22))
        self.toolButton_load_arc.setObjectName("toolButton_load_arc")
        self.lineEdit_arc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_arc.setGeometry(QtCore.QRect(90, 20, 360, 21))
        self.lineEdit_arc.setObjectName("lineEdit_arc")
        ## linelist button
        self.toolButton_load_linelist = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_load_linelist.setGeometry(QtCore.QRect(10, 45, 80, 22))
        self.toolButton_load_linelist.setObjectName("toolButton_load_linelist")
        self.lineEdit_linelist = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_linelist.setGeometry(QtCore.QRect(90, 45, 360, 21))
        self.lineEdit_linelist.setObjectName("lineEdit_linelist")
        ## show order button
        self.lineEdit_order = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_order.setEnabled(True)
        self.lineEdit_order.setGeometry(QtCore.QRect(461, 70, 113, 21))
        ## table widget
        self.tableWidget_files = QtWidgets.QTableWidget(self.centralwidget)
        #self.tableWidget_files.setGeometry(QtCore.QRect(10, 70, 500, 451))
        self.tableWidget_files.setGeometry(QtCore.QRect(10, 70, 450, 610))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_files.setFont(font)
        try:
            self.tableWidget_files.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents) ###pyqt5
        except:
            self.tableWidget_files.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents) ###pyqt5
        self.tableWidget_files.setAlternatingRowColors(True)
        self.tableWidget_files.setObjectName("tableWidget_files")
        self.tableWidget_files.setColumnCount(0)
        self.tableWidget_files.setRowCount(0)
        self.tableWidget_files.horizontalHeader().setCascadingSectionResizes(True)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(461, 110, 134, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        try:
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed) ###pyqt5
        except:
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed) ###pyqt6
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        ####----Button_upper_order
        self.pushButton_upper_order = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy.setHeightForWidth(self.pushButton_upper_order.sizePolicy().hasHeightForWidth())
        self.pushButton_upper_order.setSizePolicy(sizePolicy)
        self.pushButton_upper_order.setObjectName("pushButton_upper_order")
        self.verticalLayout.addWidget(self.pushButton_upper_order)
        ####----Button_next_order
        self.pushButton_next_order = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_next_order.setObjectName("pushButton_next_order")
        self.verticalLayout.addWidget(self.pushButton_next_order)
        ####----Button_invert_xaxis
        self.pushButton_invert_xaxis = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_invert_xaxis.setObjectName("pushButton_invert_xaxis")
        self.verticalLayout.addWidget(self.pushButton_invert_xaxis)
        ####----Button_update_table
        self.pushButton_update_table = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_update_table.setObjectName("pushButton_update_table")
        self.verticalLayout.addWidget(self.pushButton_update_table)
        ####----Button_add_line
        self.pushButton_add_line = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_add_line.setObjectName("pushButton_add_line")
        self.verticalLayout.addWidget(self.pushButton_add_line)
        ####----Button_del_line
        self.pushButton_del_line = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_del_line.setObjectName("pushButton_del_line")
        self.verticalLayout.addWidget(self.pushButton_del_line)
        ####----Button_save_line
        self.pushButton_save_line = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save_line.setObjectName("pushButton_save_line")
        self.verticalLayout.addWidget(self.pushButton_save_line)
        ####----Button_fit
        self.pushButton_fit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.verticalLayout.addWidget(self.pushButton_fit)
        ####-----fitfunction
        from pyexspec.fitfunc import Polyfitdic
        fitfunclist = list(Polyfitdic.keys())
        self.comboBox_fitfunc = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_fitfunc.addItems(fitfunclist)
        self.verticalLayout.addWidget(self.comboBox_fitfunc)
        ## show xdeg LABEL
        #self.label_xdeg =QtWidgets.QVBoxLayout()
        #self.label_xdeg.setGeometry(QtCore.QRect(511, 450, 60, 21))
        self.lineEdit_xdeg = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_xdeg.setPlaceholderText('deg(X)')
        self.lineEdit_xdeg.setEnabled(True)
        self.lineEdit_xdeg.setGeometry(QtCore.QRect(466, 450, 60, 21))
        ## show xdeg LABEL
        self.lineEdit_ydeg = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ydeg.setPlaceholderText('deg(Y)')
        self.lineEdit_ydeg.setEnabled(True)
        self.lineEdit_ydeg.setGeometry(QtCore.QRect(533, 450, 60, 21))
        font = QtGui.QFont()
        font.setBold(True)
        #font.setWeight(75)
        self.lineEdit_order.setFont(font)
        self.lineEdit_order.setObjectName("lineEdit_order")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 1430, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        ####---- find line center by Gassian fitting 
        self.CheckBoxWidget = QtWidgets.QWidget(self.centralwidget)
        self.CheckBoxWidget.setGeometry(QtCore.QRect(466, 500, 100, 21))
        self.CheckBoxWidget.setObjectName("CheckBoxWidget")
        self.layoutCheckBox = QtWidgets.QVBoxLayout(self.CheckBoxWidget)
        self.layoutCheckBox.setContentsMargins(0, 0, 0, 0)
        self.checkBox_gaussianfit = QtWidgets.QCheckBox(self.CheckBoxWidget)
        self.checkBox_gaussianfit.setObjectName("gaussianfit")
        self.layoutCheckBox.addWidget(self.checkBox_gaussianfit)
        self.checkBox_gaussianfit.setText("Gaussian Fit")
        self.lineEdit_findwindow = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_findwindow.setPlaceholderText('Find Window')
        self.lineEdit_findwindow.setEnabled(True)
        self.lineEdit_findwindow.setGeometry(QtCore.QRect(466, 521, 100, 21))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"Manually Calibrate Wave"))
        self.pushButton_update_table.setText(_translate("MainWindow", "update table"))
        self.pushButton_upper_order.setText(_translate("MainWindow", "upper order"))
        self.pushButton_next_order.setText(_translate("MainWindow", "next order"))
        self.pushButton_invert_xaxis.setText(_translate("MainWindow", "invert X-axis"))
        self.pushButton_add_line.setText(_translate("MainWindow", "add line"))
        self.pushButton_del_line.setText(_translate("MainWindow", "del line"))
        self.pushButton_save_line.setText(_translate("MainWindow", "save lines"))
        self.pushButton_fit.setText(_translate("MainWindow", "fit"))
        self.toolButton_load_arc.setText(_translate("MainWindow", "ARC..."))
        self.toolButton_load_linelist.setText(_translate("MainWindow", "LINELIST..."))
